[package]
name = "japanese-words-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
confy = { version = "0.5.1", features = ["yaml_conf"], default-features = false }
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
rand = "0.8.5"
